### PR TITLE
[dev] - Deprecrated Disabled Prop and Added Disable Prop

### LINKED ISSUE #25: Inconsistency across components with respect to "disabled" prop
*Do you want to request a feature or report a bug?*
Bug/Inconsistency

*What is the current behavior?*
The `Dropdown` and `PhoneInput` components have a `disable` prop while other components have `disabled` props.  All components should use `disabled` for consistency.

*If the current behavior is a bug, please provide the steps to reproduce.*
N/A

*Which version of react-cm-ui, and which browser / OS are affected by this issue? Did this work in previous versions of react-cm-ui?*
All released versions up to and including 1.11.11
Not browser or OS specific; it is an issue with the component prop definitions.

### PR DESCRIPTION
**Pull request by morethanfire**
Fixes #25.

### CODE REVIEW

File: src/inputs/checkbox.jsx [hunk 1]
```diff
@@ -1,13 +1,22 @@
...
+import React from 'react';
 import ClassNames from 'classnames';
 import PropTypes from 'prop-types';
 import Icon from '../dataDisplay/icon';
 
 const propTypes = {
-    align: PropTypes.oneOf([ 'left', 'right' ]),
-    checked: PropTypes.bool,
+    align: PropTypes.oneOf(['left', 'right']),
+    checked: false,
```
Comment (groberts314) [inline src/inputs/checkbox.jsx:11]: We did we change from `PropTypes.bool` to `false` here?

File: src/inputs/checkbox.jsx [hunk 2]
```diff
@@ -133,34 +197,43 @@ class Checkbox extends Component {
...
                     type="checkbox"
                     value={newValue}
                 />
 
-                <label className={labelClasses}>
-                    {label ? (
+                {/* eslint-disable-next-line jsx-a11y/label-has-associated-control */}
+                <label
+                    className={labelClasses}
+                >
```
Comment (groberts314) [inline src/inputs/checkbox.jsx:225]: Instead of suppressing the warning, couldn't we just do `htmlFor={inputId}`?

File: src/inputs/datePickerInput.jsx [hunk 3]
```diff
@@ -37,11 +91,14 @@ class DatePickerInput extends React.PureComponent {
         let inputValue;
 
         if (props.rangeFrom) {
-            inputValue = this._safeDateFormat(newDateFrom, props.locale);
+            // eslint-disable-next-line no-underscore-dangle
```
Comment (groberts314) [inline src/inputs/datePickerInput.jsx:94]: Looks like we solved the issue.  No need for suppression comments anymore, right?

File: src/inputs/durationPicker.jsx [hunk 4]
```diff
@@ -7,38 +7,59 @@ import Input from './input';
 
 const propTypes = {
     className: PropTypes.string,
+    /**
+     * A TableRow can be disabled.
```
Comment (groberts314) [inline src/inputs/durationPicker.jsx:11]: Oops ... copy-and-paste error.  Should be "A DurationPicker can be disabled."

File: src/inputs/input.jsx [hunk 5]
```diff
@@ -10,16 +17,23 @@ const propTypes = {
     autoComplete: PropTypes.oneOf(['off', 'on']),
     autoFocus: PropTypes.bool,
     className: PropTypes.string,
+    /**
+     * A DatePickerInput can be disabled.
```
Comment (groberts314) [inline src/inputs/input.jsx:21]: Oops ... copy-and-paste error.  Should be "An Input can be disabled."

File: src/inputs/input.jsx [hunk 6]
```diff
@@ -151,40 +201,36 @@ class Input extends React.PureComponent {
...
+                    if (isEmpty(newValue)) {
                         if (required) {
-                            newValue = _.isNumber(min) ? min : (_.isNumber(max)? max : 0);
+                            if (isNumber(min)) {
+                                newValue = min;
+                            } else if (isNumber(max)) {
+                                newValue = max;
+                            } else {
+                                newValue = 0;
+                            }
```
Comment (groberts314) [inline src/inputs/input.jsx:212]: Nice.  Probably to appease ESLINT "no-nested-ternary" rule I imagine.  But I happen to agree ... it does improve readability.

File: src/inputs/input.jsx [hunk 7]
```diff
@@ -151,40 +201,36 @@ class Input extends React.PureComponent {
...
-                }
-            } else {
-                if (_.isUndefined(onChange)) {
-                    this._input.value = newValue;
-                } else {
-                    onChange(newValue);
-                }
             }
 
+            console.log('newValue', newValue);
```
Comment (groberts314) [inline src/inputs/input.jsx:230]: Please remove this if the debugging is all done now! :-)

File: src/inputs/input.jsx [hunk 8]
```diff
@@ -151,40 +201,36 @@ class Input extends React.PureComponent {
...
+                            } else if (isNumber(max)) {
+                                newValue = max;
+                            } else {
+                                newValue = 0;
+                            }
                         }
                     } else {
-                        newValue = +newValue;
-                        if (_.isNumber(max)) {
+                        newValue += 1;
```
Comment (groberts314) [inline src/inputs/input.jsx:215]: Why `+= 1` here?
This looks a bit suspect.
The replaced code seems to have been `newValue = +newValue;`, using the unary `+` operator to "forcibly cast" strings to numbers I think.

File: src/inputs/input.jsx [hunk 9]
```diff
@@ -218,35 +264,51 @@ class Input extends React.PureComponent {
...
                     break;
                 default:
             }
 
-            if (_.isUndefined(onChange)) {
+            if (!isFunction(onChange)) {
+                // eslint-disable-next-line no-underscore-dangle
                 this._input.value = newValue;
             } else {
                 onChange(newValue);
```
Comment (groberts314) [inline src/inputs/input.jsx:314]: Shouldn't we use your new `setNewValue()` method for this?

File: src/inputs/input.jsx [hunk 10]
```diff
@@ -294,6 +356,21 @@ class Input extends React.PureComponent {
         return newType;
     }
 
+    setNewValue(value) {
+        const {
+            onChange,
+        } = this.props;
+
+        console.log('value', value);
```
Comment (groberts314) [inline src/inputs/input.jsx:364]: Please remove if the debugging is all done.

File: src/inputs/phoneInput.jsx [hunk 11]
```diff
@@ -13,6 +13,13 @@ const propTypes = {
     className: PropTypes.string,
     country: PropTypes.string,
     countryOptions: PropTypes.arrayOf(PropTypes.string),
+    /**
+     * A DatePickerInput can be disabled.
```
Comment (groberts314) [inline src/inputs/phoneInput.jsx:17]: Copy-and-paste error.  Should be "A PhoneInput can be disabled."

File: src/inputs/phoneInputCountryDropdown.jsx [hunk 12]
```diff
@@ -6,13 +6,21 @@ import PhoneInputCountryDropdownItem from './phoneInputCountryDropdownItem';
 import PhoneInputCountryDropdownValue from './phoneInputCountryDropdownValue';
 
 const propTypes = {
+    /**
+     * A DatePickerInput can be disabled.
```
Comment (groberts314) [inline src/inputs/phoneInputCountryDropdown.jsx:10]: Should be "A PhoneInputCountryDropdown can be disabled."

File: src/inputs/radio.jsx [hunk 13]
```diff
@@ -8,9 +15,17 @@ const propTypes = {
     align: PropTypes.oneOf(['left', 'right']),
     checked: PropTypes.oneOfType([
         PropTypes.bool,
-        PropTypes.number
+        PropTypes.number,
     ]),
+    children: PropTypes.node,
     className: PropTypes.string,
+    /**
+     * A DatePickerInput can be disabled.
```
Comment (groberts314) [inline src/inputs/radio.jsx:23]: Should be "A Radio can be disabled."

File: src/inputs/textArea.jsx [hunk 14]
```diff
@@ -10,10 +14,17 @@ const propTypes = {
     autoHeight: PropTypes.bool,
     className: PropTypes.string,
     columns: PropTypes.number,
+    /**
+     * A DatePickerInput can be disabled.
```
Comment (groberts314) [inline src/inputs/textArea.jsx:18]: Should be "A TextArea can be disabled."

File: src/inputs/textArea.jsx [hunk 15]
```diff
@@ -57,114 +100,191 @@ class TextArea extends React.Component {
...
                             <span className="text-area-required-indicator">*</span>
                         ) : null}
                     </label>
-                ) : null}
+                )}
 
                 <div className="text-area-container">
                     <textarea
-                        disabled={disabled}
+                        disabled={isDisabled}
```
Comment (groberts314) [inline src/inputs/textArea.jsx:287]: This is _precisely_ why I had a preference for `disabled` (past tense) in our component API as well.   Better harmony with the underlying native stuffs.  But c'est la vie! ;-)

File: src/templates/filtersDrawer.jsx [hunk 16]
```diff
@@ -44,6 +55,13 @@ const propTypes = {
             checkbox: PropTypes.shape({
                 checked: PropTypes.bool,
                 className: PropTypes.string,
+                /**
+                 * A DatePickerInput can be disabled.
```
Comment (groberts314) [inline src/templates/filtersDrawer.jsx:59]: Should be "A Checkbox can be disabled."  (Or maybe "A FiltersDrawer Row Item Checkbox can be disabled.")

File: src/templates/filtersDrawer.jsx [hunk 17]
```diff
@@ -111,6 +129,13 @@ const propTypes = {
             toggle: PropTypes.shape({
                 checked: PropTypes.bool,
                 className: PropTypes.string,
+                /**
+                 * A DatePickerInput can be disabled.
```
Comment (groberts314) [inline src/templates/filtersDrawer.jsx:133]: Same here; please reword for this placement versus copy-and-paste source.

File: src/inputs/checkbox.jsx (hunk 1 above)
Comment (morethanfire) [reply src/inputs/checkbox.jsx:11]: Thank you for catching this.

Comment (morethanfire) [reply src/inputs/checkbox.jsx:11]: Fixing.

File: src/inputs/checkbox.jsx (hunk 2 above)
Comment (morethanfire) [reply src/inputs/checkbox.jsx:225]: I like it... fixing.

File: src/inputs/datePickerInput.jsx (hunk 3 above)
Comment (morethanfire) [reply src/inputs/datePickerInput.jsx:94]: Fixing...

File: src/inputs/durationPicker.jsx (hunk 4 above)
Comment (morethanfire) [reply src/inputs/durationPicker.jsx:11]: Fixing...

File: src/inputs/input.jsx (hunk 5 above)
Comment (morethanfire) [reply src/inputs/input.jsx:21]: Whoops, I tried to change all those... I guess Eslint fixes finally took over my process. Fixing...

File: src/inputs/input.jsx (hunk 6 above)
Comment (morethanfire) [reply src/inputs/input.jsx:212]: I totally agree. the nested ternary methods are horrible to read.

File: src/inputs/input.jsx (hunk 7 above)
Comment (morethanfire) [reply src/inputs/input.jsx:230]: Removing...

File: src/inputs/input.jsx (hunk 9 above)
Comment (morethanfire) [reply src/inputs/input.jsx:314]: Fixing...

File: src/inputs/input.jsx (hunk 10 above)
Comment (morethanfire) [reply src/inputs/input.jsx:364]: Removing...

File: src/inputs/phoneInput.jsx (hunk 11 above)
Comment (morethanfire) [reply src/inputs/phoneInput.jsx:17]: Fixing...

File: src/inputs/phoneInputCountryDropdown.jsx (hunk 12 above)
Comment (morethanfire) [reply src/inputs/phoneInputCountryDropdown.jsx:10]: Fixing...

File: src/inputs/radio.jsx (hunk 13 above)
Comment (morethanfire) [reply src/inputs/radio.jsx:23]: Fixing...

File: src/inputs/textArea.jsx (hunk 14 above)
Comment (morethanfire) [reply src/inputs/textArea.jsx:18]: Fixing...

File: src/inputs/textArea.jsx (hunk 15 above)
Comment (morethanfire) [reply src/inputs/textArea.jsx:287]: It's kinda bitter sweet.

File: src/templates/filtersDrawer.jsx (hunk 17 above)
Comment (morethanfire) [reply src/templates/filtersDrawer.jsx:133]: Fixing...

File: src/templates/filtersDrawer.jsx (hunk 16 above)
Comment (morethanfire) [reply src/templates/filtersDrawer.jsx:59]: Fixing...

File: src/templates/filtersDrawer.jsx (hunk 17 above)
Comment (morethanfire) [reply src/templates/filtersDrawer.jsx]: Commit 7c8b691 fixes this.

File: src/templates/filtersDrawer.jsx (hunk 16 above)
Comment (morethanfire) [reply src/templates/filtersDrawer.jsx]: Commit 7c8b691 fixes this.

File: src/inputs/textArea.jsx (hunk 14 above)
Comment (morethanfire) [reply src/inputs/textArea.jsx]: Commit 7c8b691 fixes this.

File: src/inputs/radio.jsx (hunk 13 above)
Comment (morethanfire) [reply src/inputs/radio.jsx]: Commit 7c8b691 fixes this.

File: src/inputs/durationPicker.jsx (hunk 4 above)
Comment (morethanfire) [reply src/inputs/durationPicker.jsx]: Commit 7c8b691 fixes this.

File: src/inputs/datePickerInput.jsx (hunk 3 above)
Comment (morethanfire) [reply src/inputs/datePickerInput.jsx]: Commit 7c8b691 fixes this.

File: src/inputs/checkbox.jsx (hunk 2 above)
Comment (morethanfire) [reply src/inputs/checkbox.jsx]: Commit 7c8b691 fixes this.

File: src/inputs/checkbox.jsx (hunk 1 above)
Comment (morethanfire) [reply src/inputs/checkbox.jsx]: Commit 7c8b691 fixes this.

File: src/inputs/input.jsx (hunk 5 above)
Comment (morethanfire) [reply src/inputs/input.jsx]: Commit 7c8b691 fixes this.

File: src/inputs/input.jsx (hunk 7 above)
Comment (morethanfire) [reply src/inputs/input.jsx]: Commit 7c8b691 fixes this.

File: src/inputs/input.jsx (hunk 8 above)
Comment (morethanfire) [reply src/inputs/input.jsx:215]: I have tested these lines and they are working. The above also appeases Eslint's styling. Are you thinking there could be a potential regression that I am not thinking about?

File: src/inputs/input.jsx (hunk 9 above)
Comment (morethanfire) [reply src/inputs/input.jsx]: Commit 7c8b691 fixes this.

File: src/inputs/input.jsx (hunk 10 above)
Comment (morethanfire) [reply src/inputs/input.jsx]: Commit 7c8b691 fixes this.

File: src/inputs/phoneInput.jsx (hunk 11 above)
Comment (morethanfire) [reply src/inputs/phoneInput.jsx]: Commit 7c8b691 fixes this.

File: src/inputs/phoneInputCountryDropdown.jsx (hunk 12 above)
Comment (morethanfire) [reply src/inputs/phoneInputCountryDropdown.jsx]: Commit 7c8b691 fixes this.

File: src/inputs/checkbox.jsx (hunk 1 above)
Comment (groberts314) [reply src/inputs/checkbox.jsx]: Yep, looks good.  Resolving.

File: src/inputs/checkbox.jsx (hunk 2 above)
Comment (groberts314) [reply src/inputs/checkbox.jsx]: Looks good.  Resolving.

File: src/inputs/datePickerInput.jsx (hunk 3 above)
Comment (groberts314) [reply src/inputs/datePickerInput.jsx]: Looks good.  Resolving.

File: src/inputs/durationPicker.jsx (hunk 4 above)
Comment (groberts314) [reply src/inputs/durationPicker.jsx]: Looks good.  Resolving.

File: src/inputs/input.jsx (hunk 5 above)
Comment (groberts314) [reply src/inputs/input.jsx]: Confirmed component name was updated.  Resolving.

File: src/inputs/input.jsx (hunk 6 above)
Comment (groberts314) [reply src/inputs/input.jsx:212]: Resolving this thread to reduce noise on PR.

File: src/inputs/input.jsx (hunk 7 above)
Comment (groberts314) [reply src/inputs/input.jsx]: Confirmed; resolving.

File: src/inputs/input.jsx (hunk 8 above)
Comment (groberts314) [reply src/inputs/input.jsx:215]: Yeah, isn't it possible that "old" value was, say, 5, and new value is now, say, 10?  Incrementing or decrementing by 1 is not the only possible change ... right?

File: src/inputs/input.jsx (hunk 9 above)
Comment (groberts314) [reply src/inputs/input.jsx]: Yep, looks good.  Resolving.

File: src/inputs/input.jsx (hunk 10 above)
Comment (groberts314) [reply src/inputs/input.jsx]: Looks good.  Resolving.

File: src/inputs/phoneInput.jsx (hunk 11 above)
Comment (groberts314) [reply src/inputs/phoneInput.jsx]: Looks good.  Resolving.

File: src/inputs/phoneInputCountryDropdown.jsx (hunk 12 above)
Comment (groberts314) [reply src/inputs/phoneInputCountryDropdown.jsx]: Looks good.  Resolving.

File: src/inputs/radio.jsx (hunk 13 above)
Comment (groberts314) [reply src/inputs/radio.jsx]: Looks good.  Resolving.

File: src/inputs/textArea.jsx (hunk 14 above)
Comment (groberts314) [reply src/inputs/textArea.jsx]: Looks good.  Resolving.

File: src/inputs/textArea.jsx (hunk 15 above)
Comment (groberts314) [reply src/inputs/textArea.jsx:287]: Yeah, all good.  Consistency on our API is the main thing.
Resolving this thread to reduce PR noise.

File: src/templates/filtersDrawer.jsx (hunk 16 above)
Comment (groberts314) [reply src/templates/filtersDrawer.jsx]: Looks good.  Resolving.

File: src/templates/filtersDrawer.jsx (hunk 17 above)
Comment (groberts314) [reply src/templates/filtersDrawer.jsx]: Looks good.  Resolving.

File: src/inputs/input.jsx [hunk 18]
```diff
@@ -10,16 +17,23 @@ const propTypes = {
     autoComplete: PropTypes.oneOf(['off', 'on']),
     autoFocus: PropTypes.bool,
     className: PropTypes.string,
+    /**
+     * A Input can be disabled.
+     */
```
Comment (groberts314) [inline src/inputs/input.jsx:22]: Nitpick: "**_An_** Input can be disabled." ;-)
Friendly neighborhood grammar police, at your service! 😁

**Comment by groberts314** [comment]
Most of the concerns were resolved.

There is one new grammar nitpick on a documentation comment ("An" versus "A" when next word starts with a vowel -- NAB obviously).

Also I still have some concern about a possible change/regression in the `onChange()` implementation of `<Input>`s of type "number" where we seem to have changed from a unary cast of the submitted "new" value to a number to a simple increment by 1, and that seems possibly incorrect for some use cases; please see [this thread](https://github.com/saddlebackdev/react-cm-ui/pull/163#discussion_r444216311).

**Comment by groberts314** [comment]
PR Review Checkpoint Meeting Thurs 06/25/2020.
* Geoffrey re-reviewed this morning.
* Cameron to check back.

We will try and finalize and merge today!

File: src/inputs/input.jsx (hunk 18 above)
Comment (morethanfire) [reply src/inputs/input.jsx]: fixed.

File: src/inputs/input.jsx (hunk 8 above)
Comment (morethanfire) [reply src/inputs/input.jsx]: Fixed. Thanks for pointing that out and explaining what I was not seeing... I was seeing `++` for whatever reason.

File: src/inputs/input.jsx (hunk 18 above)
Comment (groberts314) [reply src/inputs/input.jsx]: Looks good.  Resolving.

File: src/inputs/input.jsx (hunk 8 above)
Comment (groberts314) [reply src/inputs/input.jsx]: The very reason we do code reviews! :-)  Get multiple people's eyes on.  All good.  Happens to the best of us.
Looks like we restored the prior code; resolving.

**Comment by groberts314** [comment]
Outstanding issues resolved.  Once we resolve the conflicts and get a passing validation build this one can be considered a :shipit:

File: src/inputs/checkbox.jsx [hunk 19]
```diff
@@ -1,13 +1,22 @@
...
 import PropTypes from 'prop-types';
 import Icon from '../dataDisplay/icon';
 
 const propTypes = {
-    align: PropTypes.oneOf([ 'left', 'right' ]),
+    align: PropTypes.oneOf(['left', 'right']),
     checked: PropTypes.bool,
     className: PropTypes.string,
+    /**
+     * A TableRow can be disabled.
```
Comment (groberts314) [inline src/inputs/checkbox.jsx:14]: Oh no ... copy and paste here.  Should be "A Checkbox can be disabled."

Comment (morethanfire) [reply src/inputs/checkbox.jsx]: Fixed

Comment (groberts314) [reply src/inputs/checkbox.jsx]: Yep, confirmed it looks good as of c17198b4.
Resolving.

**Comment by groberts314** [comment]
Looking awesome!  :shipit: quick before it accumulates any more merge conflicts! :-P
